FROM bitnami/spark:latest

# Add any additional configurations or setup if needed
COPY spark-defaults.conf /opt/bitnami/spark/conf/spark-defaults.conf
COPY spark-env.sh /opt/bitnami/spark/conf/spark-env.sh
